function Hd = FIR_lp_75
%FIR_LP_75 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.4 and the Signal Processing Toolbox 6.7.
%
% Generated on: 31-Jul-2009 16:07:11
%

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 4000;  % Sampling Frequency

Fpass = 25;              % Passband Frequency
Fstop = 70;              % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
%For plotting
% [h w] = freqz(FIR_lp_75);
% x=linspace(0,2000,length(h));
% figure;plot(x,20*log10(abs(h)));
% xlim([0 150])
% ylabel('Magnitude (dB)');xlabel('Frequency (Hz)');
% set(gca,'xtick',[0:25:150]);
% title('Low pass filter for the songbird data');
